/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pdfmodule;

import datatype.ExtractionResult;
import org.apache.commons.io.FilenameUtils;
import org.apache.pdfbox.pdmodel.PDDocument;

import java.io.File;
import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException
    {

        if(args.length < 1) {
            System.out.println("Não foi o passado o caminho para um arquivo. Abortando...");
            return;
        }

        String path = args[0];
        if(!FilenameUtils.getExtension(path).equals("pdf"))
        {
            System.out.println("O arquivo passado não é um pdf. Abortando...");
            return;
        }

        // Try to load a PDF document
        try (PDDocument document = PDDocument.load(new File(path)))
        {
            Extractor extractor = new Extractor(document,path);
            ExtractionResult extractionResult = extractor.Extract();
            Analyzer analyzer = new Analyzer(extractionResult, document);
            analyzer.analyzeDocument();
            DEBUG(extractionResult);
        }

        // DEBUG
        System.out.println("Program ended successfully.");
    }

    public static void DEBUG(ExtractionResult extractionResult)
    {
        for(int i = 0; i < extractionResult.getText().size(); i++)
        {
            System.out.println("------ TEXT FRAGMENT: " + (i + 1) + " ------");
            System.out.print("[" + extractionResult.getText().get(i).getClassification() + "]");
            System.out.println(extractionResult.getText().get(i).getContent());
            System.out.println("Xstart: " +extractionResult.getText().get(i).getxStart());
            System.out.println("XEnd: " +extractionResult.getText().get(i).getxEnd());
            System.out.println("Ystart: " +extractionResult.getText().get(i).getyStart());
            System.out.println("YEnd: " +extractionResult.getText().get(i).getyEnd());
        }

        for(int k = 0; k < extractionResult.getImage().size(); k++)
        {
            System.out.println("------ IMAGE: " + (k + 1) + " ------");
            System.out.println("[" + extractionResult.getImage().get(k).getName()+ "]");
            System.out.println("[" + extractionResult.getImage().get(k).xobject + "]");
        }
    }

}
